### PR TITLE
Fix grazing calculation

### PR DESCRIPTION
**Pull request by ChHaeni**
- add exp function to builtins
- fix wrong grazing calculation in both models
- add new and remove old technical parameters in cfg files
- correct expected output in test

### CODE REVIEW

**Comment by zaucker** [comment]
Test failures:

# Failed test 'Correct nh3_ntotal result: 269.82883478190536'
--
1460 | # at t/run-complex-model.t line 48
1461 | # expected: '269.828834781905350565908'
1462 | #      got: '269.82883478190536'
1463 | # Failed test 'Correct nh3_nanimalproduction result: 269.82883478190536'
1464 | # at t/run-complex-model.t line 50
1465 | # expected: '269.828834781905350565908'
1466 | #      got: '269.82883478190536'
1467 | t/run-complex-model.t ...............

**Comment by zaucker** [comment]
@ChHaeni you should now have write access to the Agrammon repo. With that you should be able to
- request a review
- see the continuous integration test outcomes (click on Details to the right of the continuous-integration/drone/pr  line). You can use your GitHub login there.

**Comment by ChHaeni** [comment]
> @ChHaeni you should now have write access to the Agrammon repo. With that you should be able to
> 
>     * request a review
> 
>     * see the continuous integration test outcomes (click on Details to the right of the continuous-integration/drone/pr  line). You can use your GitHub login there.

When trying to login: `Login Failed. User must be a member of an approved organization`

**Comment by zaucker** [comment]
Still test failures:

1459 | # at t/run-complex-model.t line 48
1460 | # expected: '269.828834781905350565908'
1461 | #      got: '270.850775893355'
1462 | # Failed test 'Correct nh3_nanimalproduction result: 270.850775893355'
1463 | # at t/run-complex-model.t line 50
1464 | # expected: '269.828834781905350565908'
1465 | #      got: '270.850775893355'
1466 | t/run-complex-model.t ...............

Are these tests successful locally?

@ChHaeni It seems I cannot make the test ouputs for only the Agrammon repo available to you. As our test environment has some other private repos, which for legal requirements of our other customers, I cannot make accessible to you.
I will probably first have to move the tests to GitHub actions, sorry.

**Comment by zaucker** [comment]
> > Still test failures:
> > 1459 | # at t/run-complex-model.t line 48
> > 1460 | # expected: '269.828834781905350565908'
> > 1461 | # got: '270.850775893355'
> > 1462 | # Failed test 'Correct nh3_nanimalproduction result: 270.850775893355'
> > 1463 | # at t/run-complex-model.t line 50
> > 1464 | # expected: '269.828834781905350565908'
> > 1465 | # got: '270.850775893355'
> > 1466 | t/run-complex-model.t ...............
> > Are these tests successful locally?
> > @ChHaeni It seems I cannot make the test ouputs for only the Agrammon repo available to you. As our test environment has some other private repos, which for legal requirements of our other customers, I cannot make accessible to you.
> > I will probably first have to move the tests to GitHub actions, sorry.
> 
> @zaucker no, this test fails. I used to run test `t/trun-complex-model-with-filters.t` only, didn't realize that I need to check more of them. Which ones do I need to test locally in the future?

Oh, very sorry, I didn't realize it is the other test script. I think those two are the only ones you have to run.

**Comment by jnthn** [comment]
Just to note that the builtins change here looks reasonable to me. :+1:

**Pull request merged**
