### PR TITLE
Finish tidying nhd files application

### PR DESCRIPTION
**Pull request by ChHaeni**
- Add missing variables
- Remove redundant variables
- Rename variables
- Clean up files in general

### CODE REVIEW

**Comment by ChHaeni** [comment]
Ready. Passed all tests on local machine

**Comment by zaucker** [comment]
> Ready. Passed all tests on local machine

I'll restart the tests. There are some strange errors that I don't understand and that shouldn't really be related to the files changed in this PR.

**Comment by zaucker** [comment]
> > Ready. Passed all tests on local machine
> 
> I'll restart the tests. There are some strange errors that I don't understand and that shouldn't really be related to the files changed in this PR.

Still fails. I'd like to leave that open for the moment, so that we can debug it. @ChHaeni can you please run the whole test suite on this branch locally:
`prove ... t` (without specifying a particular test script) and report the outcome?

**Comment by ChHaeni** [comment]
> > > Ready. Passed all tests on local machine
> > 
> > 
> > I'll restart the tests. There are some strange errors that I don't understand and that shouldn't really be related to the files changed in this PR.
> 
> Still fails. I'd like to leave that open for the moment, so that we can debug it. @ChHaeni can you please run the whole test suite on this branch locally:
> `prove ... t` (without specifying a particular test script) and report the outcome?

Doesn't work on my local machine:
```
 prove -e 'raku -Ilib' -vr                                                                                                                               
./t/config.t ..........................                                                                                                                                                                            
1..9                                                                                                                                                                                                               
ok 1 - Create Agrammon Config                                                                                                                                                                                      
ok 2 - Load config from file t/test-data/agrammon.cfg.yaml                                                                                                                                                         
ok 3 - Config.general as expected                                                                                                                                                                                  
ok 4 - Config.gui as expected                                                                                                                                                                                      
ok 5 - Config.model as expected                                                                                                                                                                                    
ok 6 - Config.database.name as expected                                                                                                                                                                            
ok 7 - Config.database.user as expected                                                                                                                                                                            
ok 8 - Config.database.user as expected                                                                                                                                                                            
ok 9 - Config.database.host exists                                                                                                                                                                                 
ok                                                                                                                                                                                                                 
./t/datasource-csv.t ..................                                                                                                                                                                            
ok 1 - Is a DataSource::CSV                                                                                                                                                                                        
ok 2 - Agrammon::DataSource::CSV.read() found 2 datasets                                                                                                                                                           
    ok 1 - Correct type                                                                                                                                                                                            
    ok 2 - Correct simulation name                                                                                                                                                                                 
    ok 3 - Correct data set ID                                                                                                                                                                                     
    ok 4 - Correct data for PlantProduction::AgriculturalArea                                                                                                                                                      
    ok 5 - Correct data for PlantProduction::MineralFertiliser                                                                                                                                                     
    ok 6 - Correct data for PlantProduction::RecyclingFertiliser                                                                                                                                                   
    1..6                                                                                                                                                                                                           
ok 3 - Data set 1                                                                                                                                                                                                  
    ok 1 - Correct type                                                                                                                                                                                            
    ok 2 - Correct simulation name                                                                                                                                                                                 
    ok 3 - Correct data set ID                                                                                                                                                                                     
    ok 4 - Correct data for PlantProduction::AgriculturalArea                                                                                                                                                      
    ok 5 - Correct data for PlantProduction::MineralFertiliser                                                                                                                                                     
    ok 6 - Correct data for PlantProduction::RecyclingFertiliser                                                                                                                                                   
    1..6                                                                                                                                                                                                           
ok 4 - Data set 2                                                                                                                                                                                                  
ok 5 - Is a DataSource::CSV                                                                                                                                                                                        
ok 6 - Agrammon::DataSource::CSV.read() found 2 datasets                                                                                                                                                           
    ok 1 - Correct type                                                                                                                                                                                            
    ok 2 - Correct simulation name                                                                                                                                                                                 
    ok 3 - Correct data set ID                                                                                                                                                                                     
    ok 4 - Have 2 dairy cow inputs                                                                                                                                                                                 
    ok 5 - Correct Livestock::DairyCow::Excretion::CConcentrates input                                                                                                                                             
    ok 6 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input                                                                                                                                          
    ok 7 - Correct Livestock::DairyCow input                                                                                                                                                                       
    ok 8 - Correct Livestock::DairyCow::Excretion::CConcentrates input                                                                                                                                             
    ok 9 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input                                                                                                                                          
    ok 10 - Correct Livestock::DairyCow input                                                                                                                                                                      
    1..10                                                                                                                                                                                                          
ok 7 - Data set 1                                                                                                                                                                                                  
    ok 1 - Correct type                                                                                                                                                                                            
    ok 2 - Correct simulation name                                                                                                                                                                                 
    ok 3 - Correct data set ID                                                                                                                                                                                     
    ok 4 - Have 2 dairy cow inputs                                                                                                                                                                                 
    ok 5 - Correct Livestock::DairyCow::Excretion::CConcentrates input                                                                                                                                             
    ok 6 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input                                                                                                                                          
    ok 7 - Correct Livestock::DairyCow input
    ok 8 - Correct Livestock::DairyCow::Excretion::CConcentrates input
    ok 9 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input
    ok 10 - Correct Livestock::DairyCow input
    1..10
ok 8 - Data set 2
1..8
ok
./t/datasource-db.t ...................
1..37
ok 1 - Create DB::Pg object
could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port [...]
```

**Comment by zaucker** [comment]
> > > > Ready. Passed all tests on local machine
> > > 
> > > 
> > > I'll restart the tests. There are some strange errors that I don't understand and that shouldn't really be related to the files changed in this PR.
> > 
> > 
> > Still fails. I'd like to leave that open for the moment, so that we can debug it. @ChHaeni can you please run the whole test suite on this branch locally:
> > `prove ... t` (without specifying a particular test script) and report the outcome?
> 
> Doesn't work on my local machine:
> 
> ```
>  prove -e 'raku -Ilib' -vr                                                                                                                               
> ./t/config.t ..........................                                                                                                                                                                            
> 1..9                                                                                                                                                                                                               
> ok 1 - Create Agrammon Config                                                                                                                                                                                      
> ok 2 - Load config from file t/test-data/agrammon.cfg.yaml                                                                                                                                                         
> ok 3 - Config.general as expected                                                                                                                                                                                  
> ok 4 - Config.gui as expected                                                                                                                                                                                      
> ok 5 - Config.model as expected                                                                                                                                                                                    
> ok 6 - Config.database.name as expected                                                                                                                                                                            
> ok 7 - Config.database.user as expected                                                                                                                                                                            
> ok 8 - Config.database.user as expected                                                                                                                                                                            
> ok 9 - Config.database.host exists                                                                                                                                                                                 
> ok                                                                                                                                                                                                                 
> ./t/datasource-csv.t ..................                                                                                                                                                                            
> ok 1 - Is a DataSource::CSV                                                                                                                                                                                        
> ok 2 - Agrammon::DataSource::CSV.read() found 2 datasets                                                                                                                                                           
>     ok 1 - Correct type                                                                                                                                                                                            
>     ok 2 - Correct simulation name                                                                                                                                                                                 
>     ok 3 - Correct data set ID                                                                                                                                                                                     
>     ok 4 - Correct data for PlantProduction::AgriculturalArea                                                                                                                                                      
>     ok 5 - Correct data for PlantProduction::MineralFertiliser                                                                                                                                                     
>     ok 6 - Correct data for PlantProduction::RecyclingFertiliser                                                                                                                                                   
>     1..6                                                                                                                                                                                                           
> ok 3 - Data set 1                                                                                                                                                                                                  
>     ok 1 - Correct type                                                                                                                                                                                            
>     ok 2 - Correct simulation name                                                                                                                                                                                 
>     ok 3 - Correct data set ID                                                                                                                                                                                     
>     ok 4 - Correct data for PlantProduction::AgriculturalArea                                                                                                                                                      
>     ok 5 - Correct data for PlantProduction::MineralFertiliser                                                                                                                                                     
>     ok 6 - Correct data for PlantProduction::RecyclingFertiliser                                                                                                                                                   
>     1..6                                                                                                                                                                                                           
> ok 4 - Data set 2                                                                                                                                                                                                  
> ok 5 - Is a DataSource::CSV                                                                                                                                                                                        
> ok 6 - Agrammon::DataSource::CSV.read() found 2 datasets                                                                                                                                                           
>     ok 1 - Correct type                                                                                                                                                                                            
>     ok 2 - Correct simulation name                                                                                                                                                                                 
>     ok 3 - Correct data set ID                                                                                                                                                                                     
>     ok 4 - Have 2 dairy cow inputs                                                                                                                                                                                 
>     ok 5 - Correct Livestock::DairyCow::Excretion::CConcentrates input                                                                                                                                             
>     ok 6 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input                                                                                                                                          
>     ok 7 - Correct Livestock::DairyCow input                                                                                                                                                                       
>     ok 8 - Correct Livestock::DairyCow::Excretion::CConcentrates input                                                                                                                                             
>     ok 9 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input                                                                                                                                          
>     ok 10 - Correct Livestock::DairyCow input                                                                                                                                                                      
>     1..10                                                                                                                                                                                                          
> ok 7 - Data set 1                                                                                                                                                                                                  
>     ok 1 - Correct type                                                                                                                                                                                            
>     ok 2 - Correct simulation name                                                                                                                                                                                 
>     ok 3 - Correct data set ID                                                                                                                                                                                     
>     ok 4 - Have 2 dairy cow inputs                                                                                                                                                                                 
>     ok 5 - Correct Livestock::DairyCow::Excretion::CConcentrates input                                                                                                                                             
>     ok 6 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input                                                                                                                                          
>     ok 7 - Correct Livestock::DairyCow input
>     ok 8 - Correct Livestock::DairyCow::Excretion::CConcentrates input
>     ok 9 - Correct Livestock::DairyCow::Excretion::CFeedSummerRatio input
>     ok 10 - Correct Livestock::DairyCow input
>     1..10
> ok 8 - Data set 2
> 1..8
> ok
> ./t/datasource-db.t ...................
> 1..37
> ok 1 - Create DB::Pg object
> could not connect to server: Connection refused
>         Is the server running on host "localhost" (::1) and accepting
>         TCP/IP connections on port [...]
> ```

Of course, you don't have a local database installation. Sorry ... will test on my machine(s), but probably not today.

**Comment by ChHaeni** [comment]
Now I messed it up... Sorry for the additional commits! and the possible merge conflict with pull request #211 !

**Comment by ChHaeni** [comment]
I'll restart new pull requests

**Pull request closed without merging**
